### ISSUE TITLE
npm -g can't run in sudo

### ISSUE THREAD

**Issue by kurthalex** [asseth/assethbox#1]
and path in /opt/node-v6.9.1-linux-x86/bin/npm not recognized

**Comment by Janaka-Steph** [comment]
Can you paste the exact command please ?

**Comment by kurthalex** [comment]
`
╰─➤  sudo npm -g install truffle                                          
sudo: npm: command not found
`
so I did this : 
`
╰─➤  sudo /opt/node-v6.9.1-linux-x86/bin/npm -g install truffle
/usr/bin/env: node: No such file or directory
`

**Comment by kurthalex** [comment]
but in .zshrc file I have theses lines and node should be recognized:
` 36 export NODEDIR=/opt/node-v6.9.1-linux-x86
 37 export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$NODEDIR/bin
`

**Comment by kurthalex** [comment]
Fixed by symlink in /usr/local/bin
