### ISSUE TITLE
shutdown not functional

### ISSUE THREAD

**Issue by spolrot** [asseth/assethbox#3]
When clicking on shutdown, the following error message appears:

![assethbox - shutdown issue](https://cloud.githubusercontent.com/assets/18368394/21191300/f82508e2-c224-11e6-87d2-b7bae0f9d3e2.png)

GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Operation not permitted.

Shutdown works if the user logs off (Logout then Shutdown).

**Comment by Nammalvar** [comment]
cf. http://superuser.com/questions/821976/unable-to-shut-down-from-desktop
**Solution** : add line "session required pam_systemd.so" at end of file /etc/pam.d/lxdm :
`echo "session required pam_systemd.so" >> /etc/pam.d/lxdm`
(not included in the code yet)
